@startuml

interface CourseTargetCollectionInterface

interface Collection

interface CourseTargetInformationInterface {
    +getDivision():DivisionInformationInterface
    +getGrade(): int
}

CourseTargetCollectionInterface --|> Collection

CourseTargetCollectionInterface o--> CourseTargetInformationInterface

@enduml