@startuml

interface InstructorCollectionInterface

interface Collection

interface EntityInterface {
    -getId(): int
}

interface HasFilesInterface {
    +getFiles($language: LanguageInterface): FileCollectionInterface
    +appendFile($file: FileInformationInterface): void
    +appendFiles($files: FileCollectionInterface): void
}

interface HasNameInterface {
    +getName($language: LanguageInterface): NameInterface
    +getNames(): NameCollectionInterface
    +appendName($name: NameInterface): void
    +appendNames($names: NameCollectionInterface): void
    +setName($name: NameInterface): void
    +removeNameByLanguage($language: LanguageInterface): NameInterface
    +removeNamesByLanguages($languages: LanguageCollectionInterface): NameCollectionInterface
    +removeName($name: NameInterface): boolean
    +removeNames($names: NameCollectionInterface): boolean
}

interface HasOptionalInformationInterface {
    +getOptions($language: LanguageInterface): OptionalCollectionInterface
    +appendOption($option: OptionInformationInterface): void
    +appendOptions($options: OptionalCollectionInterface): void
    +removeOption($option: OptionalInformationInterface): void
    +removeOptions($options: OptionalCollectionInterface): void
}

interface InstructorNameInterface {
    +getFullName(): string
    +setFullName($fullName: string): void
    +getFirstName(): string
    +setFirstName($firstName: string): void
    +getFamilyName(): string
    +setFamilyName($lastName: string): void
}

interface InstructorNameCollectionInterface {
    +setName($name: InstructorNameInterface): void
    +setNames($names: InstructorNameCollectionInterface): void
    +getByLanguage($language: LanguageInterface): InstructorNameInterface
    +getByLanguages($languages: LanguageCollectionInterface): InstructorNameCollectionInterface
}

interface NameInterface {
    +__construct($name: string, Language: LanguageInterface)
    +getName(): string
    +setName($name: string): void
    +getLanguage(): LanguageInterface
    +__toString(): string
}

interface NameCollectionInterface {
    +getByLanguage($language: LanguageInterface): NameInterface
    +getByLanguages($languages: LanguageCollectionInterface): NameCollectionInterface
    +setName($name: NameInterface): void
    +setNames($names: NameCollectionInterface): void
    +removeByLanguage($language: LanguageInterface): boolean
    +removeByLanguages($languages: LanguageCollectionInterface): boolean
}

interface InstructorInformationInterface {
    +getName($language: LanguageInterface): NameInterface
    +getNames(): InstructorNameCollectionInterface
    +appendName($name: InstructorNameInterface): void
    +appendNames($names: InstructorNameCollectionInterface): void
    +removeName($name: InstructorNameInterface): boolean
    +removeNames($names: NameCollectionInterface): boolean
    +getOptions($language: LanguageInterface): InstructorOptionalCollectionInterface
    +appendOption($option: InstructorOptionInformationInterface): void
    +appendOptions($options:InstructorOptionalCollectionInterface): void
    +removeOption($option: InstructorOptionalInformationInterface): void
    +removeOptions($options: InstructorOptionalCollectionInterface): void
    +getOccupation(): OccupationInterface
    +setOccupation($occupation: OccupationInterface): void
    +getCourses(): CourseCollectionInterface
    +appendCourse($course: CourseInformationInterface): void
    +appendCourses($courses: CourseCollectionInterface): void
    +getDivisions(): DivisionCollectionInterface
    +appendDivision($division: DivisionInformationInterface): void
    +appendDivisions($divisions: DivisionCollectionInterface): void
    +getUniversities(): UniversityCollectionInterface
    +appendUniversity($university: UniversityInformationInterface): void
    +appendUniversities($university: UniversityCollectionInterface): void
    +getFiles($language: LanguageInterface): FileCollectionInterface
    +appendFile($file: FileInformationInterface): void
}

InstructorCollectionInterface --|> Collection

InstructorCollectionInterface o--> InstructorInformationInterface

InstructorInformationInterface --|> EntityInterface

InstructorInformationInterface --|> HasFilesInterface

InstructorInformationInterface --|> HasNameInterface

InstructorInformationInterface --|> HasOptionalInformationInterface

InstructorInformationInterface --> InstructorNameInterface

InstructorInformationInterface --> InstructorNameCollectionInterface

InstructorNameInterface --|> NameInterface

InstructorNameCollectionInterface o--> InstructorNameInterface

InstructorNameCollectionInterface --|> NameCollectionInterface

NameCollectionInterface o--> NameInterface

NameCollectionInterface --|> Collection


@enduml